# Generated by Django 6.0 on 2025-12-12 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_approveduploader_student_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='resource_type',
            field=models.CharField(choices=[('note', 'Note'), ('pyq', 'Previous Year Question'), ('faculty', 'Faculty Note'), ('tutorial', 'Tutorial Link')], max_length=20),
        ),
    ]
