# Generated by Django 6.0 on 2025-12-12 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_resource_resource_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='resource_type',
            field=models.CharField(choices=[('note', 'Note'), ('pyq', 'Previous Year Question'), ('faculty', 'Faculty Note')], max_length=20),
        ),
    ]
